---
title: "Explore trends of climatic variables of SN (above 2300 msnm)"
author: "AJ Perez-Luque (@ajpelu)"
date: "2015 April"
output:  
    md_document:
      variant: markdown_github
---

```{r}
library('dplyr')
library("ggplot2")
```

## Prepare data
```{r}
# Prepare data
di <- '/Users/ajpelu/ownCloud/MS/CONGRESO_AEET2015/borreguiles/borreguiles_talk'

data <- read.csv(file=paste(di, '/data/climate_2300.csv', sep=''), header=TRUE, sep=";")

df <- tbl_df(data)
```

## Explore data from 1980 to 2010 
```{r}
ts_temp <- df %>% filter(ano >= 1980) %>%
  filter(codigo == 'tmin' | codigo == 'tmax') %>%
  mutate(valorC = valor / 10) %>%
  group_by(ano, codigo) %>%
  summarise_each(funs(mean, sd,se=sd(.)/sqrt(n())), valorC)
  
ggplot(ts_temp, aes(x=ano, y=mean, group=codigo)) + 
  geom_point(aes(group=codigo, shape=codigo), size=3) +
  geom_smooth(method='loess') +
  theme_bw() + xlab('year') + ylab('Temperature') + 
  theme(panel.background = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())  
```

## Comparing results 


  

```{r}


# Get mean 1980-1990 
tmin80 <- df %>% 
            filter(codigo == 'tmin', ano >= 1980, ano <= 1990) %>%
            mutate(valorC = valor / 10) %>%
            group_by(cli_celda_id) %>%
            summarise_each(funs(mean, sd,se=sd(.)/sqrt(n())), valorC)
tmin80 <- mutate(tmin80, tipo='tmin80')

tmin00 <- df %>% 
            filter(codigo == 'tmin', ano >= 2000, ano <= 2010) %>%
            mutate(valorC = valor / 10) %>%
            group_by(cli_celda_id) %>%
            summarise_each(funs(mean,sd,se=sd(.)/sqrt(n())), valorC)
tmin00 <- mutate(tmin00, tipo='tmin00')



  filter(ano >= 1980) %>% 
  filter(ano <= 1990) %>%



  summarise(media=mean(valor), 
            )



