---
title: "Explore trends of ndvi of SanJuan basin"
author: "AJ Perez-Luque (@ajpelu)"
date: "2015 April"
output:  
    md_document:
      variant: markdown_github
---

```{r}
library('plyr')
library('dplyr')
library("ggplot2")
library('broom') # tidy results
```

## Prepare data
```{r}
# Prepare data
machine <- 'ajpeluLap'

di <- paste('/Users/', machine, '/ownCloud/MS/CONGRESO_AEET2015/borreguiles/borreguiles_talk', sep='')

data <- read.csv(file=paste(di, '/data/ndvi_evi_borreguiles.csv', sep=''), header=TRUE, sep=";")
taus <- read.csv(file=paste(di, '/data/ndvi_tau_borreguiles.csv', sep=''), header=TRUE, sep=";")

df <- tbl_df(data)
df_tau <- tbl_df(taus)
```

## Explore data of summer NDVI and EVI in Borreguiles 
```{r}
# spring NDVI slope
df %>% summarise_each(funs(mean, sd,se=sd(.)/sqrt(n())), ndvi_i_primavera_pendiente)
# spring NDVI tau
df %>% summarise_each(funs(mean, sd,se=sd(.)/sqrt(n())), ndvi_i_primavera_tau)
# spring EVI slope
df %>% summarise_each(funs(mean, sd,se=sd(.)/sqrt(n())), evi_i_primavera_pendiente)
# spring EVI tau
df %>% summarise_each(funs(mean, sd,se=sd(.)/sqrt(n())), evi_i_primavera_tau)



# summer NDVI slope          
df %>% summarise_each(funs(mean, sd,se=sd(.)/sqrt(n())), ndvi_i_verano_pendiente)   
# summer NDVI tau  
df %>% summarise_each(funs(mean, sd,se=sd(.)/sqrt(n())), ndvi_i_verano_tau)
# summer EVI slope          
df %>% summarise_each(funs(mean, sd,se=sd(.)/sqrt(n())), evi_i_verano_pendiente)   
# summer EVI tau  
df %>% summarise_each(funs(mean, sd,se=sd(.)/sqrt(n())), evi_i_verano_tau)
```                   


